spring:
  cloud:
    gcp:
      config:
        enabled: true
      sql:
        instance-connection-name: nobita-gcp-project:us-central1:students-postgresql-instance
        database-name: students
  config:
    import: "sm://"
  datasource:
    username: ${sm://postgres-username}
    password: ${sm://postgres-password}
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${db.schema}

db:
  schema : student

server:
  servlet:
    context-path: /students

logging:
  level:
    org.springframework: debug
