spring:
  cloud:
    gcp:
      config:
        enabled: true
  config:
    import: "sm://"
  datasource:
    url: jdbc:postgresql://35.226.53.175/students
    username: postgres
    password: students-instance-password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${db.schema}
    hibernate:
      ddl-auto: create

db:
  schema : student

server:
  servlet:
    context-path: /students

logging:
  level:
    org.springframework: debug
