spring:
  cloud:
    gcp:
      config:
        enabled: true
  config:
    import: "sm://"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql::///students
    username: ${sm://postgres-username}
    password: ${sm://postgres-password}
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: nobita-gcp-project:us-central1:students-postgresql-instance
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: ${db.schema}

db:
  schema : student

server:
  servlet:
    context-path: /students

