spring:
  cloud:
    gcp:
      config:
        enabled: true
  config:
    import: "sm://"
  datasource:
    url: jdbc:postgresql://35.226.53.175:5432/students
    username: ${sm://postgres-username}
    password: ${sm://postgres-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${db.schema}

db:
  schema : student

server:
  servlet:
    context-path: /students

logging:
  level:
    org.springframework: debug
