spring:
  cloud:
    gcp:
      config:
        enabled: true
      sql:
        database-name: students
        instance-connection-name: nobita-gcp-project:us-central1:students-postgresql-instance
      project-id: nobita-gcp-project
  datasource:
    password: students-instance-password
    username: postgres
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

server:
  servlet:
    context-path: /students

logging:
  level:
    org.springframework: debug
