spring:
  cloud:
    gcp:
      config:
        enabled: true
      sql:
        database-name: ${sm://db-name}
        instance-connection-name: ${sm://instance-connection-name}
      project-id: nobita-gcp-project
  config:
    import: "sm://"
  datasource:
    password: ${sm://datasource-password}
    username: ${sm://datasource-username}
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

server:
  servlet:
    context-path: /students

logging:
  level:
    org.springframework: debug
